In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = {
    'text' : [
    "The cat chased the mouse in the garden.",
    "Python is a popular programming language for data science.", 
    "The garden is full of beautiful flowers and trees.",
    "Developing software requires knowledge of programming languages.",
    "Data science and machine learning use Python libraries.",
    "A mouse is a small mammal that lives in the forest.", 
    "Deep learning models are built using Python and data.", 
    "Forests are home to many animals and tall trees.",
    "Software engineering and data science are tech careers.", 
    "The small cat climbed the tall tree in the forest."
    ],
    'label' : [
        "nature", "tech", "nature", "tech", "tech", "nature", "tech", "nature", "tech", "nature"
    ]
}

df = pd.DataFrame(data)

In [3]:
df

                                                text   label
0            The cat chased the mouse in the garden.  nature
1  Python is a popular programming language for d...    tech
2  The garden is full of beautiful flowers and tr...  nature
3  Developing software requires knowledge of prog...    tech
4  Data science and machine learning use Python l...    tech
5  A mouse is a small mammal that lives in the fo...  nature
6  Deep learning models are built using Python an...    tech
7   Forests are home to many animals and tall trees.  nature
8  Software engineering and data science are tech...    tech
9  The small cat climbed the tall tree in the for...  nature

In [4]:
df['label'] = df['label'].replace(['nature', 'tech'], [1, 0])

In [5]:
df

                                                text  label
0            The cat chased the mouse in the garden.      1
1  Python is a popular programming language for d...      0
2  The garden is full of beautiful flowers and tr...      1
3  Developing software requires knowledge of prog...      0
4  Data science and machine learning use Python l...      0
5  A mouse is a small mammal that lives in the fo...      1
6  Deep learning models are built using Python an...      0
7   Forests are home to many animals and tall trees.      1
8  Software engineering and data science are tech...      0
9  The small cat climbed the tall tree in the for...      1

In [6]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

# Stemming in NLP

In [7]:
from nltk.tokenize import word_tokenize, sent_tokenize, PunktSentenceTokenizer

In [8]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
ps

In [9]:
sen = "The server crashed due to a memory leak in the database."
sen

'The server crashed due to a memory leak in the database.'

In [10]:
word_tokens = word_tokenize(sen)
word_tokens

['The',
 'server',
 'crashed',
 'due',
 'to',
 'a',
 'memory',
 'leak',
 'in',
 'the',
 'database',
 '.']

In [11]:
for word in word_tokens :
    print(word, " --- ", ps.stem(word))

The  ---  the
server  ---  server
crashed  ---  crash
due  ---  due
to  ---  to
a  ---  a
memory  ---  memori
leak  ---  leak
in  ---  in
the  ---  the
database  ---  databas
.  ---  .

# Lemmatization in NLP

In [12]:
sen

'The server crashed due to a memory leak in the database.'

In [13]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()
wnl

In [14]:
for word in word_tokens :
    print(word, " --- ", ps.stem(word), " --- ", wnl.lemmatize(word, pos = 'v'))

The  ---  the  ---  The
server  ---  server  ---  server
crashed  ---  crash  ---  crash
due  ---  due  ---  due
to  ---  to  ---  to
a  ---  a  ---  a
memory  ---  memori  ---  memory
leak  ---  leak  ---  leak
in  ---  in  ---  in
the  ---  the  ---  the
database  ---  databas  ---  database
.  ---  .  ---  .

# Tokenization in NLP

# NLTK

In [15]:
new_sen = "Developing software requires knowledge of programming languages. The small cat climbed the tall tree in the forest."
new_sen

'Developing software requires knowledge of programming languages. The small cat climbed the tall tree in the forest.'

In [16]:
from nltk.tokenize import word_tokenize, sent_tokenize, PunktSentenceTokenizer

In [17]:
word_tokens = word_tokenize(new_sen)
word_tokens

['Developing',
 'software',
 'requires',
 'knowledge',
 'of',
 'programming',
 'languages',
 '.',
 'The',
 'small',
 'cat',
 'climbed',
 'the',
 'tall',
 'tree',
 'in',
 'the',
 'forest',
 '.']

In [18]:
sent_tokens = sent_tokenize(new_sen)
sent_tokens

['Developing software requires knowledge of programming languages.',
 'The small cat climbed the tall tree in the forest.']

In [19]:
len(sent_tokens)

2

In [20]:
toks = PunktSentenceTokenizer().tokenize(new_sen)
toks

['Developing software requires knowledge of programming languages.',
 'The small cat climbed the tall tree in the forest.']

# Named Entity Tokenization using NLTK

In [21]:
word_tokens

['Developing',
 'software',
 'requires',
 'knowledge',
 'of',
 'programming',
 'languages',
 '.',
 'The',
 'small',
 'cat',
 'climbed',
 'the',
 'tall',
 'tree',
 'in',
 'the',
 'forest',
 '.']

In [22]:
from nltk import pos_tag, ne_chunk

In [23]:
pos_tags = pos_tag(word_tokens)
pos_tags

[('Developing', 'VBG'),
 ('software', 'NN'),
 ('requires', 'VBZ'),
 ('knowledge', 'NN'),
 ('of', 'IN'),
 ('programming', 'VBG'),
 ('languages', 'NNS'),
 ('.', '.'),
 ('The', 'DT'),
 ('small', 'JJ'),
 ('cat', 'NN'),
 ('climbed', 'VBD'),
 ('the', 'DT'),
 ('tall', 'JJ'),
 ('tree', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('forest', 'NN'),
 ('.', '.')]

In [24]:
chunks = ne_chunk(pos_tags)
print(chunks)

(S
  Developing/VBG
  software/NN
  requires/VBZ
  knowledge/NN
  of/IN
  programming/VBG
  languages/NNS
  ./.
  The/DT
  small/JJ
  cat/NN
  climbed/VBD
  the/DT
  tall/JJ
  tree/NN
  in/IN
  the/DT
  forest/NN
  ./.)

# Text Vectorizer

In [25]:
df

                                                text  label
0            The cat chased the mouse in the garden.      1
1  Python is a popular programming language for d...      0
2  The garden is full of beautiful flowers and tr...      1
3  Developing software requires knowledge of prog...      0
4  Data science and machine learning use Python l...      0
5  A mouse is a small mammal that lives in the fo...      1
6  Deep learning models are built using Python an...      0
7   Forests are home to many animals and tall trees.      1
8  Software engineering and data science are tech...      0
9  The small cat climbed the tall tree in the for...      1

## Text Processing¶

In [26]:
import string 
punc = string.punctuation
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [27]:
from nltk.corpus import stopwords

In [28]:
en_stopwords = set(stopwords.words('english'))
en_stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [29]:
ben_stopwords = set(stopwords.words('bengali'))
ben_stopwords

{'অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'চেষ্টা',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'ঠিক',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নয়',
 'না',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেই',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'নয়',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিশেষ',
 'বিষয়টি',
 'বেশ',
 'বেশি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুধু',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়'}

In [30]:
df.columns

Index(['text', 'label'], dtype='object')

In [31]:
def preprocess_text(text) :
    remove_punc = [char for char in text if char not in punc]
    clean_words = ''.join(remove_punc)
    split_words = clean_words.split()
    text = [word for word in split_words if word.lower() not in en_stopwords]
    return text

In [32]:
df.text = df.text.apply(preprocess_text)
df

                                                text  label
0                       [cat, chased, mouse, garden]      1
1  [Python, popular, programming, language, data,...      0
2          [garden, full, beautiful, flowers, trees]      1
3  [Developing, software, requires, knowledge, pr...      0
4  [Data, science, machine, learning, use, Python...      0
5              [mouse, small, mammal, lives, forest]      1
6  [Deep, learning, models, built, using, Python,...      0
7        [Forests, home, many, animals, tall, trees]      1
8  [Software, engineering, data, science, tech, c...      0
9          [small, cat, climbed, tall, tree, forest]      1

In [33]:
def lemmatized_text(text) :
    clean_text = []
    for word in text :
        clean_text.append(wnl.lemmatize(word))

    return ' '.join(clean_text)

In [34]:
df.text = df.text.apply(lemmatized_text)
df

                                                text  label
0                            cat chased mouse garden      1
1   Python popular programming language data science      0
2                  garden full beautiful flower tree      1
3  Developing software requires knowledge program...      0
4   Data science machine learning use Python library      0
5                     mouse small mammal life forest      1
6        Deep learning model built using Python data      0
7                 Forests home many animal tall tree      1
8      Software engineering data science tech career      0
9                 small cat climbed tall tree forest      1

# CountVectorizer¶

In [35]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [36]:
cv = CountVectorizer()
cv

CountVectorizer()

In [37]:
cv_x = cv.fit_transform(df.text)
cv_x

<10x39 sparse matrix of type '<class 'numpy.int64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [38]:
cv_x.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]], dtype=int64)

In [39]:
df['text'][0]

'cat chased mouse garden'

In [40]:
cv_df = pd.DataFrame(cv_x.toarray(), index = df['text'], columns = cv.get_feature_names_out())
cv_df

,animal,beautiful,built,career,cat,chased,climbed,data,deep,developing,...,python,requires,science,small,software,tall,tech,tree,use,using
text,,,,,,,,,,,,,,,,,,,,,
cat chased mouse garden,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Python popular programming language data science,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0
garden full beautiful flower tree,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Developing software requires knowledge programming language,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,0,0
Data science machine learning use Python library,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,1,0
mouse small mammal life forest,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
Deep learning model built using Python data,0,0,1,0,0,0,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
Forests home many animal tall tree,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
Software engineering data science tech career,0,0,0,1,0,0,0,1,0,0,...,0,0,1,0,1,0,1,0,0,0
small cat climbed tall tree forest,0,0,0,0,1,0,1,0,0,0,...,0,0,0,1,0,1,0,1,0,0

# TfidfVectorizer

In [41]:
tfidf = TfidfVectorizer()
tfidf

TfidfVectorizer()

In [42]:
tfidf_x = tfidf.fit_transform(df['text'])
tfidf_x

<10x39 sparse matrix of type '<class 'numpy.float64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [43]:
tfidf_x.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.47761213,
        0.56183624, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.47761213, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.47761213, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33107819, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.42564193, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.50070139, 0.42564193, 0.37238639,
        0.        , 0.37238639, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.48360622, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48360622, 0.        , 0.        , 0.48360622,
        0.41110947, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3596722 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.43988604,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.43988604, 0.37394332, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.37394332, 0.        ,
        0.43988604, 0.        , 0.        , 0.37394332, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.28814117, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.37044109,
        0.43576621, 0.        , 0.43576621, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.32409218,
        0.        , 0.32409218, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.43576621, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4163931 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48982158, 0.        , 0.48982158, 0.        ,
        0.        , 0.4163931 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4163931 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.41837663, 0.        , 0.        ,
        0.        , 0.        , 0.27664268, 0.41837663, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.35565836,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.41837663, 0.        , 0.        , 0.        , 0.31115904,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.41837663],
       [0.43536779, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.43536779, 0.        ,
        0.        , 0.43536779, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.43536779,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.3701024 ,
        0.        , 0.32379586, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.4606284 , 0.        ,
        0.        , 0.        , 0.30458077, 0.        , 0.        ,
        0.4606284 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.34258292, 0.        , 0.39157622, 0.        ,
        0.4606284 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.40326502,
        0.        , 0.47437845, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40326502, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40326502, 0.        , 0.40326502,
        0.        , 0.35280924, 0.        , 0.        ]])

In [44]:
tfidf_df = pd.DataFrame(tfidf_x.toarray(), index = df['text'], columns = tfidf.get_feature_names_out())
tfidf_df

,animal,beautiful,built,career,cat,chased,climbed,data,deep,developing,...,python,requires,science,small,software,tall,tech,tree,use,using
text,,,,,,,,,,,,,,,,,,,,,
cat chased mouse garden,0.000000,0.000000,0.000000,0.000000,0.477612,0.561836,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Python popular programming language data science,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.331078,0.000000,0.000000,...,0.372386,0.000000,0.372386,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
garden full beautiful flower tree,0.000000,0.483606,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.359672,0.000000,0.000000
Developing software requires knowledge programming language,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.439886,...,0.000000,0.439886,0.000000,0.000000,0.373943,0.000000,0.000000,0.000000,0.000000,0.000000
Data science machine learning use Python library,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.288141,0.000000,0.000000,...,0.324092,0.000000,0.324092,0.000000,0.000000,0.000000,0.000000,0.000000,0.435766,0.000000
mouse small mammal life forest,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.416393,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Deep learning model built using Python data,0.000000,0.000000,0.418377,0.000000,0.000000,0.000000,0.000000,0.276643,0.418377,0.000000,...,0.311159,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.418377
Forests home many animal tall tree,0.435368,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.370102,0.000000,0.323796,0.000000,0.000000
Software engineering data science tech career,0.000000,0.000000,0.000000,0.460628,0.000000,0.000000,0.000000,0.304581,0.000000,0.000000,...,0.000000,0.000000,0.342583,0.000000,0.391576,0.000000,0.460628,0.000000,0.000000,0.000000
small cat climbed tall tree forest,0.000000,0.000000,0.000000,0.000000,0.403265,0.000000,0.474378,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.403265,0.000000,0.403265,0.000000,0.352809,0.000000,0.000000

# Word2Vec

In [45]:
from gensim.models import Word2Vec, KeyedVectors
import nltk

In [46]:
df

                                                text  label
0                            cat chased mouse garden      1
1   Python popular programming language data science      0
2                  garden full beautiful flower tree      1
3  Developing software requires knowledge program...      0
4   Data science machine learning use Python library      0
5                     mouse small mammal life forest      1
6        Deep learning model built using Python data      0
7                 Forests home many animal tall tree      1
8      Software engineering data science tech career      0
9                 small cat climbed tall tree forest      1

In [47]:
text_token = []
for sen in df['text'] :
    text_token.append(word_tokenize(sen))

text_token

[['cat', 'chased', 'mouse', 'garden'],
 ['Python', 'popular', 'programming', 'language', 'data', 'science'],
 ['garden', 'full', 'beautiful', 'flower', 'tree'],
 ['Developing',
  'software',
  'requires',
  'knowledge',
  'programming',
  'language'],
 ['Data', 'science', 'machine', 'learning', 'use', 'Python', 'library'],
 ['mouse', 'small', 'mammal', 'life', 'forest'],
 ['Deep', 'learning', 'model', 'built', 'using', 'Python', 'data'],
 ['Forests', 'home', 'many', 'animal', 'tall', 'tree'],
 ['Software', 'engineering', 'data', 'science', 'tech', 'career'],
 ['small', 'cat', 'climbed', 'tall', 'tree', 'forest']]

In [48]:
model = Word2Vec(text_token, min_count = 1)
model

In [49]:
model_df = pd.DataFrame(model.wv.vectors, index = model.wv.index_to_key, columns = [i for i in range(model.wv.vectors.shape[1])])

In [50]:
model_df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
tree,-0.000537,0.000237,0.005105,0.009011,-0.009309,-0.007121,0.006464,0.008977,-0.005017,-0.003768,...,0.001630,0.000188,0.003474,0.000223,0.009628,0.005054,-0.008913,-0.007044,0.000902,0.006388
science,-0.008622,0.003666,0.005187,0.005742,0.007467,-0.006167,0.001106,0.006048,-0.002842,-0.006172,...,0.001089,-0.001577,0.002197,-0.007883,-0.002719,0.002661,0.005347,-0.002391,-0.009508,0.004508
data,0.000088,0.003075,-0.006817,-0.001370,0.007668,0.007348,-0.003669,0.002644,-0.008323,0.006208,...,-0.004509,0.005699,0.009179,-0.004102,0.007967,0.005369,0.005882,0.000511,0.008217,-0.007022
Python,-0.008244,0.009300,-0.000196,-0.001967,0.004597,-0.004102,0.002744,0.006947,0.006063,-0.007517,...,-0.007423,-0.001061,-0.000795,-0.002562,0.009692,-0.000460,0.005870,-0.007451,-0.002504,-0.005553
tall,-0.007135,0.001243,-0.007177,-0.002239,0.003715,0.005829,0.001200,0.002106,-0.004104,0.007220,...,0.003142,-0.004707,0.005281,-0.004230,0.002646,-0.008053,0.006199,0.004822,0.000786,0.003024
forest,-0.008726,0.002137,-0.000874,-0.009314,-0.009431,-0.001418,0.004441,0.003714,-0.006502,-0.006883,...,0.009066,0.008943,-0.008207,-0.003007,0.009905,0.005105,-0.001593,-0.008698,0.002968,-0.006682
small,0.008132,-0.004457,-0.001068,0.001006,-0.000193,0.001147,0.006115,-0.000019,-0.003248,-0.001512,...,-0.002698,0.000443,-0.003538,-0.000421,-0.000709,0.000822,0.008196,-0.005738,-0.001659,0.005569
learning,0.008166,-0.004441,0.008988,0.008257,-0.004440,0.000297,0.004276,-0.003923,-0.005563,-0.006519,...,0.002059,-0.004000,-0.008245,0.006282,-0.001940,-0.000670,-0.001773,-0.004538,0.004063,-0.004273
language,-0.009583,0.008947,0.004162,0.009240,0.006647,0.002925,0.009806,-0.004422,-0.006810,0.004224,...,-0.005086,0.001135,0.002882,-0.001534,0.009945,0.008345,0.002415,0.007119,0.005896,-0.005583
programming,-0.005156,-0.006668,-0.007777,0.008311,-0.001982,-0.006855,-0.004154,0.005144,-0.002869,-0.003750,...,-0.008977,0.008592,0.004047,0.007470,0.009746,-0.007290,-0.009040,0.005836,0.009391,0.003507
garden,0.007088,-0.001565,0.007947,-0.009490,-0.008035,-0.006644,-0.003998,0.004995,-0.003819,-0.008324,...,0.007513,0.001493,-0.001263,0.005766,-0.005637,0.000037,0.009458,-0.005485,0.003818,-0.008116
mouse,0.009771,0.008167,0.001280,0.005098,0.001405,-0.006459,-0.001428,0.006454,-0.004618,-0.003998,...,0.004775,-0.003258,-0.009268,0.003788,0.007167,-0.005633,-0.007868,-0.002975,-0.004932,-0.002317
cat,-0.001942,-0.005260,0.009449,-0.009292,0.004501,0.005402,-0.001403,0.009012,0.009885,-0.005481,...,0.002646,-0.002559,0.006449,-0.007653,0.003411,0.000491,0.008731,0.005979,0.006817,0.007816
climbed,-0.009505,0.009572,-0.007769,-0.002637,-0.004901,-0.004965,-0.008015,-0.007783,-0.004554,-0.001277,...,0.008384,0.007239,0.001727,-0.001340,-0.005877,-0.004538,0.008650,-0.003130,-0.006340,0.009873
career,0.007693,0.009121,0.001134,-0.008329,0.008426,-0.003696,0.005743,0.004392,0.009687,-0.009291,...,0.007100,0.001901,0.005200,0.006376,0.001911,-0.006127,-0.000007,0.008270,-0.006096,0.009440
tech,-0.007191,0.004234,0.002163,0.007442,-0.004890,-0.004565,-0.006098,0.003300,-0.004497,0.008522,...,-0.003480,0.003492,-0.005795,-0.008750,-0.005515,0.006747,0.006415,0.009440,0.007054,0.006757
engineering,0.001300,-0.009803,0.004588,-0.000538,0.006333,0.001784,-0.003129,0.007761,0.001555,0.000055,...,0.007013,0.004829,0.008683,0.007094,-0.005693,0.007240,-0.009294,-0.002587,-0.007757,0.004193
Software,0.001798,0.007049,0.002941,-0.006979,0.007714,-0.005987,0.009000,0.002960,-0.004015,-0.004687,...,0.009130,0.003589,0.006567,-0.003612,0.006796,0.007243,-0.002134,-0.001859,0.003612,-0.007034
animal,0.009736,-0.009780,-0.006499,0.002784,0.006432,-0.005367,0.002752,0.009121,-0.006815,-0.006100,...,0.007441,-0.004298,0.004577,0.009090,0.003043,0.003139,0.004062,-0.002701,0.003825,0.000338
many,0.005627,0.005497,0.001829,0.005749,-0.008968,0.006559,0.009226,-0.004207,0.001608,-0.005234,...,-0.000959,0.001310,-0.008595,0.008749,-0.009208,-0.009625,-0.008512,0.007313,0.005466,0.009249
home,0.002568,0.000846,-0.002543,0.009367,0.002758,0.004099,-0.001175,0.000906,0.006621,-0.000725,...,-0.006486,0.003119,0.000792,0.008325,0.006841,-0.002913,0.002540,-0.001666,-0.009452,-0.002618
Forests,0.001330,0.006542,0.009982,0.009062,-0.008015,0.006495,-0.005714,-0.000972,0.000484,0.006585,...,0.009625,-0.007364,-0.000111,-0.002563,-0.006363,-0.001387,-0.005243,0.009065,-0.005794,0.003687
using,-0.000238,0.004219,0.002114,0.009996,0.000627,-0.005467,-0.001178,0.002073,-0.003374,-0.007850,...,0.001872,-0.001605,-0.008167,0.003258,0.001968,-0.008735,-0.000675,0.000075,-0.000005,0.008710
built,-0.002509,-0.005903,0.007483,-0.007260,-0.008966,-0.001790,-0.008367,0.000390,0.001946,-0.002469,...,0.003905,-0.006998,-0.005295,-0.007938,-0.005130,0.007071,0.009641,0.002155,0.000640,0.009524
model,-0.004975,-0.001284,0.003281,-0.006409,-0.009703,-0.009263,0.009025,0.005374,-0.004792,-0.008333,...,0.000942,-0.008535,0.000256,0.000370,0.003943,-0.009472,0.009709,-0.006975,0.005764,-0.009432
Deep,0.009649,0.007325,0.001262,-0.003405,-0.000451,0.000423,-0.006409,0.005745,0.002371,0.003778,...,-0.005736,-0.002211,0.008125,-0.003905,-0.001189,-0.009285,-0.009477,0.008883,-0.005703,0.005053
life,-0.006965,-0.002458,-0.008023,0.007500,0.006129,0.005260,0.008380,-0.000698,-0.009312,0.009118,...,0.008453,-0.006288,-0.001766,-0.008181,-0.006675,-0.008580,0.003933,0.002738,0.005614,0.002571
mammal,0.002114,0.005735,-0.002116,0.003172,0.008444,0.000388,0.006295,-0.006744,0.006576,0.004689,...,0.001540,0.001291,0.002923,-0.009396,0.003254,0.005465,0.005286,0.004440,-0.008086,-0.004060
library,0.008356,-0.000573,-0.009439,0.004784,-0.006051,0.006678,0.005377,-0.005038,0.002572,0.005411,...,-0.001196,0.005273,-0.005942,-0.004975,-0.004949,-0.004758,-0.007984,-0.009761,0.007581,0.008001
use,-0.004282,-0.009330,-0.001871,-0.003707,0.009091,0.002938,-0.005972,-0.003356,-0.009910,0.001942,...,-0.000035,0.008171,0.002361,0.008253,0.003336,0.005422,0.005101,-0.007634,-0.005784,0.001227
machine,0.000193,0.002150,0.001058,0.007594,-0.004428,0.000325,0.007016,0.002263,0.004225,0.004301,...,-0.000007,0.002476,0.005472,0.001606,0.009829,0.003720,-0.007178,-0.001412,-0.008357,-0.005340
Data,-0.002185,-0.009712,0.009296,0.002025,-0.001184,-0.005521,-0.008497,-0.009885,0.008938,-0.002518,...,0.008150,0.001498,-0.008790,-0.007604,0.001565,-0.009535,-0.007415,0.002007,-0.002911,-0.009159
knowledge,0.006415,-0.008951,-0.007345,-0.001751,0.001698,-0.001034,-0.005204,0.006579,0.008783,-0.007412,...,-0.006253,0.000508,0.004292,-0.002111,0.000894,0.003710,0.009710,0.002176,0.009500,-0.005830
requires,0.004801,-0.003631,-0.004265,0.001220,-0.004131,-0.005630,0.003146,0.008341,-0.006549,-0.009116,...,-0.005485,-0.009503,0.006970,-0.005538,-0.009326,0.002596,-0.004977,-0.007363,0.009735,-0.001585
software,-0.001510,-0.004036,-0.004398,-0.004630,-0.005601,-0.005307,-0.008021,0.009523,0.006397,-0.003611,...,0.000147,-0.002288,0.005309,-0.003417,-0.002617,0.008791,-0.009156,-0.003418,-0.002920,0.005668
Developing,0.007942,-0.006451,0.005794,-0.000213,-0.009033,-0.002441,-0.001584,-0.004479,-0.000795,-0.005238,...,-0.000351,0.002694,0.004737,0.000143,-0.005775,-0.000593,0.002183,0.008298,-0.003595,-0.009849
flower,0.005384,0.009810,-0.007054,-0.000582,-0.005068,0.006432,0.009658,-0.000330,0.005140,0.006533,...,-0.009067,0.003417,0.005347,0.003471,0.007797,0.001652,0.006271,0.008832,-0.000941,-0.000807
beautiful,0.002227,-0.007533,0.005628,-0.005000,-0.003271,-0.001833,0.008216,0.002246,-0.000908,-0.002845,...,-0.001058,0.001372,0.000087,-0.002203,0.008548,0.000106,0.006419,0.003991,-0.007203,-0.002124
full,-0.007776,-0.006758,-0.003154,0.006615,-0.000834,0.008884,-0.002292,-0.005304,0.003915,0.002216,...,-0.004079,-0.008243,-0.008038,0.003506,-0.009561,0.005707,-0.002912,-0.009173,-0.005136,0.007744
popular,-0.001721,0.006406,-0.009277,-0.009147,-0.005202,0.000952,-0.007176,-0.009446,-0.008886,-0.000463,...,-0.001366,-0.002463,-0.004717,-0.004262,0.000127,0.001649,-0.009449,0.006076,-0.001681,-0.002974
chased,-0.004794,-0.004317,-0.004801,-0.009804,-0.000777,-0.007792,-0.004812,-0.007375,0.009936,-0.001356,...,0.009199,0.001805,0.009710,-0.009907,-0.001501,0.006900,-0.001463,-0.001757,-0.007079,-0.005666